sudo: required

language: generic

services:
  - docker

env:
  - OPP_PATH=/root/omnetpp-5.2-linux/bin RUN_FINGERPRINT_TESTS=yes
  - OPP_PATH=/root/omnetpp-5.2-windows/bin
  - OPP_PATH=/root/omnetpp-5.2-macosx/bin

before_install:
  - docker pull torokati44/omnetpp-core-triplatform

script:
  - docker run -ti --env RUN_FINGERPRINT_TESTS --env OPP_PATH -v /home/travis/build/$TRAVIS_REPO_SLUG:/$TRAVIS_REPO_SLUG torokati44/omnetpp-core-triplatform /bin/bash -c "export PATH=$OPP_PATH:\\\\\$PATH; cd /$TRAVIS_REPO_SLUG && make makefiles && make MODE=release && if [ x$RUN_FINGERPRINT_TESTS = xyes ]; then cd tests/fingerprint && ./runDefaultTests.sh -e opp_run_release; fi"